---
title: EasyNative Themes
author: easynative.github.io
email: get@easynative.app
description: EsyNative that will empower content editors to construct their own webpages.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
